//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp29 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class MainWindowModelSet : global::System.Configuration.ApplicationSettingsBase {
        
        private static MainWindowModelSet defaultInstance = ((MainWindowModelSet)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MainWindowModelSet())));
        
        public static MainWindowModelSet Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Save")]
        public string SaveCommand {
            get {
                return ((string)(this["SaveCommand"]));
            }
            set {
                this["SaveCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Load")]
        public string LoadCommand {
            get {
                return ((string)(this["LoadCommand"]));
            }
            set {
                this["LoadCommand"] = value;
            }
        }
    }
}
